### ISSUE TITLE
Planned Feature: Gene-level expression estimates

### ISSUE THREAD

**Issue by kingsfordgroup** [kingsfordgroup/sailfish#16]
The user will, optionally, be able to provide a gene-to-transcript mapping, and Sailfish will produce expression estimates aggregated at the gene level.  Currently, the plan is to allow the gene <=> transcript mapping to be given as either a simple text file, each line of the format `transcript<tab>gene`, or as a gff file.

**Comment by billytcl** [comment]
Any progress on this feature? I would really love to try this in my current work. A lot of other programs require quite a bit of parameter "massaging" -- I prefer using sailfish because it is clean and easy to use.

**Comment by rob-p** [comment]
Hi @billytcl,

  Yes; this feature is already implemented in both salmon and the development version of sailfish; the latter of which is only available right now via source.  Since I recommend using salmon anyway, this feature should already be available.  However, it will also be present in the next binary release of sailfish (which will be available after a few more blocking bugs have been addressed).

**Comment by rob-p** [comment]
Since this features is already live in the codebase (in the develop branch) and already part of all of the salmon binaries.  I'm going to close this ticket.
