### ISSUE TITLE
Low number of reads counted

### ISSUE THREAD

**Issue by myojencards** [kingsfordgroup/sailfish#33]
I have been using Sailfish to count reads from a rat RNA-seq experiment.
I used these commands..
sailfish index -t path to Rattus_norvegicus.Rnor_5.0.cdna.all.fa (ftp://ftp.ensembl.org/pub/release-76/fasta/rattus_norvegicus/cdna/) -k 30 -o /Sailfish/30mer -p 24

sailfish quant -i /home/jknapp5/genomes/igenomes/rat/Rattus_norvegicus/Ensembl/Rnor_5.0/Sequence/Sailfish/30mer -l "T=PE:O=><:S=U" -1 Sample_R1.fasta -2 Sample_R2.fasta -o Sample_out -p 24

 /home/jknapp5/genesum-master/bin/genesum -e quant_bias_corrected.sf -g /home/jknapp5/genomes/genome_index_sailfish/rat/ensembl/Rattus_norvegicus.Rnor_5.0.75.gtf -k gene_id -o genex_quant_bias_corrected.sf

It seems to work fine but it is counting less than half the reads that are mapped by star and tophat and that is resulting in fewer differential expressed genes.

Total counted(star-htcount)	11485975		16974141	13168823	12713090	15263528	11891131		12341120		12264430
total counted (tophat-htcount)	11230278		16558980	12848296	12442179	14920805	11631414		12049568	11988935
total counted (sailfish) 	632405		561191		556256		548207		546057		544889		552987		564331

EdgeR
star (DE-genes) 1178
tophat (DE-genes) 1857
sailfish (DE-genes)  69 only 45 overlap with star or tophat.
Do you know why this is? I counted using kmers of 15, 20, 25, and 30 the results ranged from 50-100 DE-genes. Any help would be appreciated.

**Comment by rob-p** [comment]
Hi @myojencards,

  The main issue here is the way that "reads" are counted.  Since Sailfish works entirely based on k-mers, it extrapolates the read mapping count from the exact k-mer overlapping count.  This is a *highly* (likely overly) conservative method (there are some more details in the Google User Group).  We'll probably address this in an up-coming release by changing the rule by which expected read counts are derived from k-mer mapping counts.  However, expected read counts are derived from k-mer mapping counts.  However, an even better solution is to give Salmon a try.  There, you can directly compare the *lightweight alignment-based* and *traditional alignment-based* estimates (Salmon is capable of producing both using the same inference algorithm).  Further, since Salmon deals with allocation in terms of fragments from the start, it avoid the tricky issue of having to extrapolate from k-mers to reads.

--Rob

**Comment by rob-p** [comment]
This is no longer true as of Sailfish v0.7.0 and you should be able to use the number of reads without trouble.  The speed and accuracy should also noticeably improve.
