### ISSUE TITLE
Provide option to skip update check

### ISSUE THREAD

**Issue by jdidion** [kingsfordgroup/sailfish#76]
I run salmon on a cluster in which network access is blocked for running jobs, therefore salmon hangs for some time while checking for updates. Please provide a command line option to skip this check.

**Comment by kingsfordgroup** [comment]
The option:

	--no-version-check

should do this now. Let us know if it doesn’t work.

Carl

**Comment by rob-p** [comment]
For the record, the `--no-version-check` flag should be passed *before* any salmon command (this is because the version check itself happens before any other command is executed).  So, the command would look something like:

```
> salmon --no-version-check quant [quant options]
```

Since this should resolve the issue, I'm going to close this ticket.  Please re-open it if you find this doesn't work for you or encounter a related issue.
