### ISSUE TITLE
Sailfish-Paired end single replicate study

### ISSUE THREAD

**Issue by misrak** [kingsfordgroup/sailfish#90]
Hello All,

I wanted to know if I can use Sailfish for single replicate study for three different conditions.

Thank you!

**Comment by rob-p** [comment]
Hi @misrak,

  I presume your goal is to test for differential gene / transcript expression across conditions?  Sailfish will give you accurate estimates of transcript expression in each sample (i.e. in each single replicate of each condition).  Additionally, you can use the `--numBootstraps` option to generate bootstraps for each sample which will allow for an estimate of the *technical* variance of the abundance estimates.  However, I'll parrot the now-standard warning — you *should be very wary of* attempting to make DE calls with only a single replicate per-condition.  This advice is independent of how accurate your quantification tool is (i.e. this advice holds even if you *perfectly* estimate transcript abundance in each sample), since a single replicate per-condition prevents you from estimating each condition's biological variability.  In this case, downstream DE tools (like DESeq2) may treat different samples as replicates for the purpose of estimating variability (I refer you to the [excellent DESeq2 vignette](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.pdf) for more details).  **TLDR** — Sailfish will quantify these samples just fine, and you can run DE tools on the results, but best practices **highly-recommend** having multiple replicates per-condition for the purposes of DE.

**Comment by misrak** [comment]
Thank you so much. :)

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Mon, Mar 21, 2016 at 6:50 AM -0700, "Rob Patro" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @misrak<https://github.com/misrak>,

I presume your goal is to test for differential gene / transcript expression across conditions? Sailfish will give you accurate estimates of transcript expression in each sample (i.e. in each single replicate of each condition). Additionally, you can use the --numBootstraps option to generate bootstraps for each sample which will allow for an estimate of the technical variance of the abundance estimates. However, I'll parrot the now-standard warning - you should be very wary of attempting to make DE calls with only a single replicate per-condition. This advice is independent of how accurate your quantification tool is (i.e. this advice holds even if you perfectly estimate transcript abundance in each sample), since a single replicate per-condition prevents you from estimating each condition's biological variability. In this case, downstream DE tools (like DESeq2) may treat different samples as replicates for the purpose of estimating variability (I refer you to the excellent DESeq2 vignette<https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.pdf> for more details). TLDR - Sailfish will quantify these samples just fine, and you can run DE tools on the results, but best practices highly-recommend having multiple replicates per-condition for the purposes of DE.

-
